# Generated by Django 4.1.1 on 2022-09-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_users_age_alter_users_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Crmuser',
        ),
    ]
