# Generated by Django 4.1.1 on 2022-09-10 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_users_crmuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryDetail',
            fields=[
                ('model_name', models.CharField(choices=[('igtblu', 'IGTBLU'), ('igtred', 'IGTRED'), ('igtred+', 'IGTRED+')], default='', max_length=100)),
                ('battery_serial_num', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('battery_type', models.CharField(choices=[('1', '24'), ('2', '48'), ('3', '60'), ('4', '72')], default='', max_length=100, unique=True)),
                ('bms_type', models.CharField(choices=[('ion', 'ION'), ('electrifuel', 'ELECTRIFUEL')], default='', max_length=100)),
                ('iot_type', models.CharField(choices=[('tarckmate', 'TRACKMATE'), ('electrifuel', 'ELECTRIFUEL'), ('aeidth', 'AEIDTH')], default='', max_length=100)),
                ('iot_imei_number', models.CharField(max_length=1000)),
                ('sim_number', models.CharField(blank=True, default='', max_length=12)),
                ('warrenty_start_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('warrenty_end_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('assigned_owner', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('in_swap_station', 'IN_SWAP_STATION'), ('in_vehicle', 'IN_VEHICLE'), ('idel', 'IDEL'), ('damaged', 'DAMAGED')], max_length=50)),
                ('battery_cell_chemistry', models.CharField(default='', max_length=50)),
                ('battery_pack_nominal_voltage', models.CharField(default='', max_length=50)),
                ('battery_pack_nominal_charge_capacity', models.CharField(default='', max_length=50)),
                ('charging_status', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
