# Generated by Django 4.1.1 on 2022-09-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_batterydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batterydetail',
            name='charging_status',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
    ]
