# Generated by Django 4.0.7 on 2022-09-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryDetail',
            fields=[
                ('model_name', models.CharField(blank=True, choices=[('igtblu', 'IGTBLU'), ('igtred', 'IGTRED'), ('igtred+', 'IGTRED+')], default='', max_length=100)),
                ('battery_serial_num', models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('battery_type', models.CharField(choices=[('24', '24'), ('48', '48'), ('60', '60'), ('72', '72')], default='', max_length=100)),
                ('bms_type', models.CharField(choices=[('ion', 'ION'), ('electrifuel', 'ELECTRIFUEL')], default='', max_length=100)),
                ('iot_type', models.CharField(choices=[('tarckmate', 'TRACKMATE'), ('electrifuel', 'ELECTRIFUEL'), ('aeidth', 'AEIDTH')], default='', max_length=100)),
                ('iot_imei_number', models.CharField(max_length=1000)),
                ('sim_number', models.CharField(blank=True, default='', max_length=12)),
                ('warrenty_start_date', models.DateField(blank=True, default='')),
                ('warrenty_duration', models.DateField(blank=True, default='')),
                ('assigned_owner', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('in_swap_station', 'IN_SWAP_STATION'), ('in_vehicle', 'IN_VEHICLE'), ('idel', 'IDEL'), ('damaged', 'DAMAGED')], default='', max_length=50)),
                ('battery_cell_chemistry', models.CharField(default='', max_length=50)),
                ('battery_pack_nominal_voltage', models.CharField(default='', max_length=50)),
                ('battery_pack_nominal_charge_capacity', models.CharField(default='', max_length=50)),
                ('charging_status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Crmuser',
            fields=[
                ('username', models.CharField(default=20, max_length=20)),
                ('email', models.EmailField(default='', max_length=20, primary_key=True, serialize=False)),
                ('contact', models.CharField(default='', max_length=12)),
                ('password', models.CharField(default='', max_length=20)),
                ('password_conformation', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
