# Generated by Django 4.0.7 on 2022-09-27 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irasusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 5, 49, 47, 689580)),
        ),
    ]
