# Generated by Django 4.0.7 on 2022-09-27 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irasusapp', '0002_alter_crmuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 5, 50, 2, 784103)),
        ),
    ]
