# Generated by Django 4.0.7 on 2022-09-27 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irasusapp', '0003_alter_crmuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 6, 3, 26, 386733)),
        ),
    ]
