# Generated by Django 4.0.7 on 2022-09-27 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irasusapp', '0004_alter_crmuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crmuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 6, 15, 18, 632609)),
        ),
    ]
